services:
  db:
    image: postgres:14-alpine
    container_name: questions-db
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    # ONLY FOR DEBUG PURPOSES
    environment:
      - "POSTGRES_USER=questions"
      - "POSTGRES_PASSWORD=questions"
      - "POSTGRES_DB=questions"
volumes:
  postgres_data:
